spring.application.name=users
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/users
spring.r2dbc.username=postgres
spring.r2dbc.password=root

spring.flyway.enabled=true

spring.flyway.url=jdbc:postgresql://localhost:5432/users
spring.flyway.user=postgres
spring.flyway.password=root

# Not for production use, but fine for debugging.
# Will include binding errors in the controller response.
spring.web.error.include-binding-errors=always

# Not for production use, but fine for debugging.
# Includes a 'message' field in the controller response.
spring.web.error.include-message=always